import type { Metadata } from "next";
import { Inter, Lato, Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import AuthProvider from "@/provider/AuthProvider";
import Authorization from "@/components/authentication/Authorization";
import StoreProvider from "@/provider/StoreProvider";
import Navbar from "@/components/navbar/Navbar";

const font = Lato({
  subsets: ["latin"],
  weight: ['100', '300', '400', '700', '900'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} mx-auto max-w-[2560px] px-6`}>
        <StoreProvider>
          <AuthProvider>
            <Authorization>
              <Navbar />
              <div className=" mt-16">{children}</div>
            </Authorization>
          </AuthProvider>
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
