import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import AuthProvider from "@/provider/AuthProvider";
import Navbar from "@/components/navbar/Navbar";
import Authorization from "@/components/authentication/Authorization";
import StoreProvider from "@/provider/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} mx-auto max-w-[2560px] px-6`}>
        <StoreProvider>
          <AuthProvider>
            <Authorization>
              <Navbar />
              {children}
            </Authorization>
          </AuthProvider>
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
